version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: current_actions_postgres
    environment:
      POSTGRES_USER: current_actions_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: current_actions
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/schemas/current_actions.sql:/docker-entrypoint-initdb.d/init.sql

  current-actions:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: current_actions_service
    depends_on:
      - postgres
    environment:
      - DB_CONNECTION=postgresql://current_actions_user:password@postgres:5432/current_actions
      # Если тебе надо что-то ещё передать через ENV
    ports:
      - "8080:8080"
