version: "3.8"

services:
  # --- База данных для current-actions ---
  postgres-current-actions:
    image: postgres:16
    container_name: current_actions_postgres_db
    environment:
      POSTGRES_USER: current_actions_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: current_actions
    ports:
      - "5432:5432" # Связываем порт 5432 контейнера с портом 5432 хоста
    volumes:
      - ./services/current-actions/postgresql/schemas/current_actions.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U current_actions_user -d current_actions"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Сервис current-actions ---
  current-actions:
    build:
      context: ./services/current-actions # Путь к директории сервиса
      dockerfile: Dockerfile
    container_name: current_actions_service
    depends_on:
      postgres-current-actions:
        condition: service_healthy 
    # Переменные окружения для current-actions (если они переопределяют config_vars.yaml)
    # environment:
    #   DB_CONNECTION: 'postgresql://current_actions_user:password@postgres_current_actions:5432/current_actions'
    ports:
      - "8080:8080" # Связываем порт 8080 контейнера с портом 8080 хоста
    networks:
      - app_network

  # --- База данных для sometime-later ---
  postgres-sometime-later:
    image: postgres:16
    container_name: sometime_later_postgres_db
    environment:
      POSTGRES_USER: sometime_later_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sometime_later
    ports:
      - "5433:5432" # Связываем порт 5432 контейнера с портом 5433 хоста (чтобы не было конфликта с 5432 от current-actions)
    volumes:
      - ./services/sometime-later/postgresql/schemas/sometime_later.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sometime_later_user -d sometime_later"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Сервис sometime-later ---
  sometime-later:
    build:
      context: ./services/sometime-later # Путь к директории сервиса
      dockerfile: Dockerfile
    container_name: sometime_later_service
    depends_on:
      postgres-sometime-later:
        condition: service_healthy
    # Переменные окружения для sometime-later (если они переопределяют config_vars.yaml)
    # environment:
    #   DB_CONNECTION: 'postgresql://sometime_later_user:password@postgres_sometime_later:5432/sometime_later_db'
    ports:
      - "8081:8080" # Связываем порт 8080 контейнера с портом 8081 хоста (чтобы не было конфликта с 8080 от current-actions)
    networks:
      - app_network

# Определяем сеть, чтобы сервисы могли общаться по именам
networks:
  app_network:
    driver: bridge
