openapi: 3.0.3
info:
    title: Current Actions API
    description: API для управления заметками в системе SECOND BRAIN
    version: 1.0.0

paths:
    /calendar/v1/generate:
        post:
            summary: Генерация файла события для календаря .ics
            operationId: generateEvent
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/GenerateEventRequest'
            responses:
                201:
                    description: Файл успешно сгенерирован
                400:
                    description: Некорректные параметры запроса
                    content:
                        application/json:
                            schema:
                                $ref: 'definitions.yaml#/components/schemas/Error'
    
components:
    schemas:
        GenerateEventRequest:
            type: object
            additionalProperties: false
            properties:
                user_id:
                    type: integer
                    format: int64
                    description: Идентификатор пользователя
                summary:
                    type: string
                    description: Название события
                description:
                    type: string
                    description: Описание события
                dtstart:
                    type: string
                    format: date-time
                    description: Дата и время начала события
                dtend:
                    type: string
                    format: date-time
                    description: Дата и время окончания события
            required:
              - user_id
              - summary
              - dtstart
