worker-threads: 4
worker-fs-threads: 2
logger-level: info

is-testing: false

server-port: 8080

dbconnection: 'postgresql://current_actions_user:password@localhost:5432/current_actions'

sometime-later-client.base-url: http://localhost:8080
