worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is-testing: true

server-port: 8080

dbconnection: 'postgresql://testsuite@localhost:15433/sometime-later_sometime_later'

current-actions-client:
  base-url: http://localhost:8080
